### ISSUE TITLE
Missing Vital Packages

### ISSUE THREAD

**Issue by realQuartzi** [WheelyCatStudios/torte#10]
**Describe the bug**
Project default does not contain specific packages and global settings.

**Additional context**
We are missing the new Input System which can be retrieved from the Package Manager in Unity.
TextmeshPro has not yet been introduced to the project as well. ( It is a unity default )
Sprite Layer Alignment. ( For sorting sprites dependent on their y value ) 

**Screenshots**
Input System
![image](https://user-images.githubusercontent.com/34374881/102416880-f33a7300-3ffa-11eb-87f6-fff11365ae0f.png)

TextmeshPro
![image](https://user-images.githubusercontent.com/34374881/102416969-1b29d680-3ffb-11eb-8726-094dc1a8bedb.png)

Sprite Layer Alignment
![image](https://user-images.githubusercontent.com/34374881/102417337-c63a9000-3ffb-11eb-965e-eac63c5dc521.png)

**Development Version**
* Branch name: main

**Comment by Shinkson47** [comment]
@realQuartzi please could you clarify what you mean about the sprite layer alignment not being included? 

I tested changing the values shown, and they appear in the change list as expected.

![image](https://i.ibb.co/vVJFBHV/Screen-Shot-2020-12-17-at-11-57-37-am.png)

**Comment by realQuartzi** [comment]
> @realQuartzi please could you clarify what you mean about the sprite layer alignment not being included?
> 
> I tested changing the values shown, and they appear in the change list as expected.
> 
> ![image](https://camo.githubusercontent.com/064d1b8aec7e1a8d9d3eeecde7ad4dcc7b56c498c630bc91a3538afcb298e826/68747470733a2f2f692e6962622e636f2f76564a464248562f53637265656e2d53686f742d323032302d31322d31372d61742d31312d35372d33372d616d2e706e67)

Why this is important is so that Sprites are layered correctly throughout the project.
And example shown here... ( Red being the sprite which is supposed to appear behind the blue sprite )
[Without y set to 1]
![image](https://user-images.githubusercontent.com/34374881/102501733-0e9a9200-407e-11eb-91d7-76ba4e11642e.png)
[With y set to 1]
![image](https://user-images.githubusercontent.com/34374881/102501823-25d97f80-407e-11eb-9bc5-70222c737d13.png)

The settings have to be x:0 y:1 z:0

**Comment by Shinkson47** [comment]
I see, so what you're asking for is the values 0, 1, 0 by default. Gotcha.

**Comment by realQuartzi** [comment]
Yes sir :)
