### ISSUE TITLE
Story : Scene switching contact trigger

### ISSUE THREAD

**Issue by Shinkson47** [WheelyCatStudios/torte#18]
Game objects can be used to switch between scenes upon contact with the player
 
## Epic:
#14 : Environment
 
 
## Stories:
- [ ] As a player, i can enter a structures by walking into it's door

- [ ] As a player, i can move between different map cells by following a path and walking off the edge, like shown:

https://user-images.githubusercontent.com/50697488/102894411-f601f180-445a-11eb-8db0-8c1689da5004.mov

- [x] As a contributor, i can add a scene trigger component to any object, so that i can make it trigger a scene transition 
- [x] As a contributor, i can freely resize the trigger zone, so that i can control the area that will cause a trigger
- [ ] As a contributor, it's possible for me to prevent a player from entering areas they should *yet* be able to enter, so that i can force them to follow the flow of the story, and complete a task before gaining access to an area area.

 
## Acceptance criteria
- [x] It's not possible for scenes to get stuck looping. I.e you enter a building, landing on the exit trigger and immediately exit.
- [ ] It's clear to the user what scene is being loaded, whether it be an interior, or a new world cell.
- [ ] Walking into a GameObject, visible or not, can change to a pre specified scene.
- [ ] Scene transition zones are lockable, such that a player can be prevented from entering without completing another task first, which would unlock the area.

**Comment by realQuartzi** [comment]
Do we actually "SWITCH" scenes or is it more of a teleport?
Like is every "zone" in the game going to be in a seperate scene or in seperate space.

**Comment by galdchen** [comment]
> Do we actually "SWITCH" scenes or is it more of a teleport?
> Like is every "zone" in the game going to be in a seperate scene or in seperate space.

It would be best to have each area in its own scene. We can additively load scenes as the player approaches the trigger zone to give us the benefits of having both zones in the same scene, while also allowing us to control when the scene is preloaded to better optimize game performance. With both scenes loaded we can have a transition between them, or in the case of walking in a house or into a tunnel, have a cut transition.

**Comment by Shinkson47** [comment]
closed by #45
