### ISSUE TITLE
WASD Character movement

### ISSUE THREAD

**Issue by Shinkson47** [WheelyCatStudios/torte#3]
The player can move the player character using the W, A, S, and D keys as is customary.
 
## Epic:
#2 : Entity Movement
 
 
## Story:
- [x] As an entity, i want WASD to move the player in the corresponding cardinal directions, such that i can traverse the environment and explore my surroundings freely.
 
 
## Acceptance criteria
- [x] Holding `W` Moves the PC North,
- [x] Holding `A` Moves the PC West,
- [x] Holding `S` Moves the PC South,
- [x] Holding `D` Moves the PC West.
- [x] Holding a key performs a continuous movement, until the key is released.
- [x] The player cannot move faster than the entity max speed.

**Comment by funisinfinite** [comment]
Smooth curve acceleration and deceleration do not fit current game style and adds unrealistic movement property.

**Comment by Shinkson47** [comment]
@funisinfinite there's a few different movement controllers, which're you referring to?

**Comment by realQuartzi** [comment]
@Shinkson47 I believe what he is talking about are the 2 unmarked criteria, and he does have a good point. "Smooth curve acceleration" really does not seem to be fitting well with game style, and becomes more of an annoyance as the user has to wait for his movement to become "regular." <3

**Comment by Shinkson47** [comment]
Ah, I understand. Thinking about it, I agree. 

We could very well scratch those since the camera controller Fran has going illiminates the need for it - the camera rubber bands and gives the exact feel I was imagining.

Looking back, my explaination doesn't really match what I had in mind, so I'm sorry for the confusion.

Since we have a few, we need to decide on what were doing at some point; which controller are we keeping? Should we merge some features of them together to make one super controller?

**Comment by realQuartzi** [comment]
I was thinking on letting the teams first merge there projects into develop, and then look at both of them in the develop branch and then start merging the codes together to make them more modular and organized.

**Comment by Shinkson47** [comment]
closed by #36
