### ISSUE TITLE
Camera system

### ISSUE THREAD

**Issue by atallahhezbor** [WheelyCatStudios/torte#8]
## Description

The camera system allows the player view to be manipulated by the movement of a target component or target event
 
## Goals

The movement should be smooth, not abrupt. 
Avoid vertigo, dizziness and other qualitatively unpleasant feelings
Player's view can be shifted to other non-player objects and characters
User should have a clear understanding of where their character is at all times

 

## Acceptance criteria / User Stories

When moving the character across an environment, the camera follows their movement smoothly
A lock node system is in place such that tracking targets can be modified away from the player character

### Stories
- [x] #7 - The camera moves with the player
- [x] #9 - Focus on specified objects
 
## Timeline
This epic is partially blocked by #2: Entity movement. 
But creation of the camera controller and tracking logic can be in place before then

## Prioritisation / Product value

Essential to user experience, Camera movement is almost as crucial as player movement. 

With limited / no camera movement, the player's ability to move and explore the environment is extremely limited.

P1.

**Comment by Shinkson47** [comment]
closed by #36
